'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function FlyingCrow({ step, test }, props) {
	const group = useRef()
	const { nodes, materials, animations } = useGLTF(
		'/3D/crow_fly-transformed.glb'
	)
	const { actions } = useAnimations(animations, group)

	/*
	 * start :
	 *       -22.5, 40, 60 // position
	 *       0.9, -0.2, -0.4 // rotation
	 *
	 *
	 *  end :
	 *       0 0 0 // position
	 *       0 0 0 // rotation
	 *
	 * */

	// useFrame(
	//     (state, delta) => {
	//         // show position
	//         console.log("position :", test.current.matrix.elements[12], test.current.matrix.elements[13], test.current.matrix.elements[14])
	//         // show rotation
	//         console.log("rotation :", test.current.matrix.elements[0], test.current.matrix.elements[1], test.current.matrix.elements[2])
	//     }
	// )

	useEffect(() => {
		if (step === 1) {
			group.current.position.set(0, 60, 0)
		}
		if (step === 2) {
			materials.crow.transparent = true

			// lerp opacity to 1
			materials.crow.opacity = 1

			console.log('uuu', animations)
			actions.flyingCrowAction.play()

			console.log('aaaa', group.current.position)
		}

		if (step === 3) {
			materials.crow.transparent = true

			// lerp opacity to 1
			materials.crow.opacity = 1

			// // then blend color to black after 1 second
			// setTimeout(() => {
			//     materials.crow.color = "black";
			// }, 1000)
		} else {
			// step 0, 1 or 2
			// materials.crow.transparent = true;
			// materials.crow.opacity = 0;   // set to 0 later
		}
	}, [step])

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="flyingCrow">
					<group name="Bone">
						<mesh
							name="crow"
							geometry={nodes.crow.geometry}
							material={materials.crow}
							position={[-0.27, -0.228, -39.947]}
							rotation={[-0.028, 0, -0.725]}
							scale={0.881}
						/>
					</group>
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('/3D/crow_fly-transformed.glb')
