/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\3D\crow_fly.glb --transform 
Files: .\public\3D\crow_fly.glb [277.55KB] > C:\Users\breva\Desktop\repos\breval\crow_fly-transformed.glb [33.32KB] (88%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/crow_fly-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="flyingCrow">
          <group name="Bone">
            <mesh name="crow" geometry={nodes.crow.geometry} material={materials.crow} position={[-0.27, -0.228, -39.947]} rotation={[-0.028, 0, -0.725]} scale={0.881} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/crow_fly-transformed.glb')
