"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import {Html, MeshPortalMaterial, useGLTF} from '@react-three/drei'
import * as THREE from "three";

export function Model(props) {
    const { nodes, materials } = useGLTF('/crow_fly.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.body.geometry}
                material={materials.crow}
                position={[1.73, -0.228, 0.053]}
                rotation={[-0.028, 0, -0.725]}
                scale={0.881}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_.geometry}
                material={materials.crow}
                position={[1.063, 0.049, -3.42]}
                rotation={[0.044, -0.681, 0]}
                scale={[0.191, 0.057, 0.191]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_002.geometry}
                // material={materials.crow}
                position={[1.204, 0.108, -3.987]}
                rotation={[0.064, -0.873, 0]}
                scale={[0.149, 0.044, 0.149]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.wing.geometry}
                material={materials.crow}
                position={[2.387, -0.004, -0.925]}
                rotation={[0.003, 0.019, 0]}
                scale={[0.347, 0.095, 0.627]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_003.geometry}
                material={materials.crow}
                position={[1.557, 0.186, -4.394]}
                rotation={[0.09, -1.032, 0]}
                scale={[0.168, 0.05, 0.168]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_004.geometry}
                material={materials.crow}
                position={[1.832, 0.283, -4.879]}
                rotation={[0.11, -1.179, 0]}
                scale={[0.133, 0.04, 0.133]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_005.geometry}
                material={materials.crow}
                position={[2.188, 0.361, -5.099]}
                rotation={[0.129, -1.275, 0]}
                scale={[0.12, 0.036, 0.12]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_010.geometry}
                material={materials.crow}
                position={[3.807, 0.264, -4.032]}
                rotation={[-2.988, -0.947, -Math.PI]}
                scale={[0.051, 0.015, 0.051]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_011.geometry}
                material={materials.crow}
                position={[0.696, 0.017, -3.066]}
                rotation={[0.023, -0.491, 0]}
                scale={[0.152, 0.045, 0.152]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_012.geometry}
                material={materials.crow}
                position={[0.437, -0.003, -2.658]}
                rotation={[0.005, -0.3, -0.001]}
                scale={[0.157, 0.047, 0.157]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_013.geometry}
                material={materials.crow}
                position={[0.231, -0.041, -2.234]}
                rotation={[-0.027, -0.15, -0.008]}
                scale={[0.142, 0.042, 0.142]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_014.geometry}
                material={materials.crow}
                position={[0.11, -0.069, -1.809]}
                rotation={[-0.065, -0.034, -0.017]}
                scale={[0.142, 0.042, 0.142]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_015.geometry}
                material={materials.crow}
                position={[-0.014, -0.071, -1.404]}
                rotation={[-0.108, 0.036, -0.029]}
                scale={[0.113, 0.034, 0.113]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_016.geometry}
                material={materials.crow}
                position={[-0.039, -0.033, -0.949]}
                rotation={[-0.148, 0.158, -0.044]}
                scale={[0.13, 0.039, 0.13]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_009.geometry}
                material={materials.crow}
                position={[3.999, 0.536, -5.25]}
                rotation={[-2.96, -1.057, -Math.PI]}
                scale={[0.085, 0.025, 0.085]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_008.geometry}
                material={materials.crow}
                position={[3.803, 0.629, -5.992]}
                rotation={[-2.972, -1.119, -Math.PI]}
                scale={[0.085, 0.025, 0.085]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_007.geometry}
                material={materials.crow}
                position={[3.185, 0.603, -6.259]}
                rotation={[-2.99, -1.334, -Math.PI]}
                scale={[0.085, 0.025, 0.085]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_006.geometry}
                material={materials.crow}
                position={[2.616, 0.535, -6.368]}
                rotation={[-3.01, -1.48, Math.PI]}
                scale={[0.085, 0.025, 0.085]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_018.geometry}
                material={materials.crow}
                position={[2.238, 0.287, -4.308]}
                rotation={[0.119, -1.265, 0]}
                scale={[0.092, 0.027, 0.092]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_019.geometry}
                material={materials.crow}
                position={[3.546, 0.426, -4.55]}
                rotation={[-2.974, -1.147, Math.PI]}
                scale={[0.065, 0.019, 0.065]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_020.geometry}
                material={materials.crow}
                position={[3.396, 0.531, -5.078]}
                rotation={[-2.968, -1.167, -Math.PI]}
                scale={[0.065, 0.019, 0.065]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_021.geometry}
                material={materials.crow}
                position={[2.939, 0.513, -5.189]}
                rotation={[-2.981, -1.382, Math.PI]}
                scale={[0.065, 0.019, 0.065]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_022.geometry}
                material={materials.crow}
                position={[2.545, 0.478, -5.26]}
                rotation={[-2.996, -1.503, Math.PI]}
                scale={[0.065, 0.019, 0.065]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_023.geometry}
                material={materials.crow}
                position={[1.261, 0.073, -3.169]}
                rotation={[0.045, -0.681, 0]}
                scale={[0.157, 0.047, 0.157]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_024.geometry}
                material={materials.crow}
                position={[1.372, 0.131, -3.647]}
                rotation={[0.063, -0.871, 0]}
                scale={[0.123, 0.037, 0.123]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_025.geometry}
                material={materials.crow}
                position={[1.662, 0.182, -3.983]}
                rotation={[0.085, -1.032, 0]}
                scale={[0.139, 0.041, 0.139]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_026.geometry}
                material={materials.crow}
                position={[1.889, 0.258, -4.382]}
                rotation={[0.105, -1.179, 0]}
                scale={[0.11, 0.033, 0.11]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_027.geometry}
                material={materials.crow}
                position={[0.578, 0.006, -2.485]}
                rotation={[0.002, -0.311, -0.002]}
                scale={[0.142, 0.042, 0.142]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_034.geometry}
                material={materials.crow}
                position={[0.334, -0.016, -2.102]}
                rotation={[-0.033, -0.15, -0.009]}
                scale={[0.131, 0.039, 0.131]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_028.geometry}
                material={materials.crow}
                position={[0.193, -0.04, -1.696]}
                rotation={[-0.072, -0.034, -0.019]}
                scale={[0.136, 0.041, 0.136]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_029.geometry}
                material={materials.crow}
                position={[0.161, -0.036, -1.336]}
                rotation={[-0.105, 0.036, -0.028]}
                scale={[0.104, 0.031, 0.104]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_030.geometry}
                material={materials.crow}
                position={[0.194, -0.003, -0.933]}
                rotation={[-0.111, 0.102, -0.031]}
                scale={[0.119, 0.036, 0.119]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_031.geometry}
                material={materials.crow}
                position={[0.378, 0.033, -0.595]}
                rotation={[-0.129, 0.157, -0.043]}
                scale={[0.147, 0.044, 0.147]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_017.geometry}
                material={materials.crow}
                position={[1.024, 0.043, -2.785]}
                rotation={[0.026, -0.5, 0]}
                scale={[0.167, 0.05, 0.167]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_032.geometry}
                material={materials.crow}
                position={[3.579, 0.304, -4.006]}
                rotation={[-2.991, -1.069, -Math.PI]}
                scale={[0.047, 0.014, 0.047]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_033.geometry}
                material={materials.crow}
                position={[0.839, 0.009, -0.73]}
                rotation={[-0.085, -0.028, -0.053]}
                scale={[0.171, 0.051, 0.171]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_.geometry}
                material={materials.crow}
                position={[-0.241, 0.204, 0.034]}
                rotation={[-0.346, -0.764, -0.155]}
                scale={[0.094, 0.028, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_001.geometry}
                material={materials.crow}
                position={[-0.58, 0.268, 0.055]}
                rotation={[-0.371, -0.659, -0.176]}
                scale={[0.094, 0.028, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_002.geometry}
                material={materials.crow}
                position={[-0.77, 0.338, 0.161]}
                rotation={[-0.362, -0.524, -0.177]}
                scale={[0.094, 0.028, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_003.geometry}
                material={materials.crow}
                position={[-0.876, 0.407, 0.327]}
                rotation={[-0.338, -0.365, -0.168]}
                scale={[0.094, 0.028, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_004.geometry}
                material={materials.crow}
                position={[-0.99, 0.414, 0.28]}
                rotation={[-0.288, -0.063, -0.159]}
                scale={[0.094, 0.028, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_001.geometry}
                material={materials.crow}
                position={[-0.418, 0.274, 0.076]}
                rotation={[-0.385, -0.79, -0.184]}
                scale={[0.087, 0.026, 0.087]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.feather_002_1.geometry}
                material={materials.crow}
                position={[-0.61, 0.308, 0.069]}
                rotation={[-0.366, -0.612, -0.174]}
                scale={[0.087, 0.026, 0.087]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_005.geometry}
                material={materials.crow}
                position={[-0.78, 0.374, 0.176]}
                rotation={[-0.355, -0.478, -0.173]}
                scale={[0.087, 0.026, 0.087]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tails_006.geometry}
                material={materials.crow}
                position={[-0.871, 0.437, 0.335]}
                rotation={[-0.329, -0.319, -0.166]}
                scale={[0.087, 0.026, 0.087]}
            />
        </group>
    )
}

useGLTF.preload('/crow_fly.glb')

